### ISSUE TITLE
MCM menu for Elder Souls - Death

### ISSUE THREAD

**Issue by Mojopoop** [GuitarBarbarianOfThunder/eldersouls#124]
**Request**
The idea of a dark souls like dying and leveling system is neat but personally I'd rather not have the death system and limited saves. It would be great if you could tweak the exact options you want. I know it's supposed to be the main thing of the mod but just having the option to opt out of that mechanic would be lovely.

**Additional context**
The nexus page for Elder Souls - Death (Ashes) says it has a MCM menu but its nowhere to be found in game.

**Comment by rshackleton** [comment]
Just because of the occasional Skyrim crashes it would be nice to disable the save limitation. I would personally reload for crashes only and keep the death system enabled but at least it provides players with options.

Can be frustrating to lose progress due to a crash, or needing to exit the game and have to spend time hunting down a bed.

I've mitigated this a little by using Campfire to be able to effectively save anywhere by sleeping.

**Comment by realVato** [comment]
Hey rshackleton,

I want to ask what is your system and is it on SSD? I get hard and random crashes 15 minutes into the game, and I would think it is because the whole thing is installed on HDD.

**Comment by jdsmith2816** [comment]
Sorry but I won't be implementing an MCM into the ESD mod.  The fact that Ashes has one is irrelevant.

**Comment by zediious** [comment]
For any wanting to circumvent this, you can spawn an elder scroll - break with the console once, and it will always stay in your inventory when you save.
